# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Glen Johnson
email:
description: >- # this means to ignore newlines until "baseurl:"
  Website of saxophonist and woodwind tutor, Glen Johnson. Live performer, arranger, 
  session musician and woodwind tutor. 
# twitter_username: glenjohnson1977
# github_username: username
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
# theme: minimal-mistakes-jekyll
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name   : "Glen Johnson"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Musician. Saxophonist. Arranger. Educator."
  location: "Dunmow, Essex."
  links:
    - label: "glen@glenjohnson.co.uk"
      icon: "far fa-fw fa-envelope"
      url: "mailto:glen@glenjohnson.co.uk"
    - label: "+44 (0) 7808 507363"
      icon: "fas fa-fw fa-phone"
      url: "tel:+447808507363"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/Glenjohnsonsax"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/glenjohnsonmusic"

footer:
  links:
    - label: "glen@glenjohnson.co.uk"
      icon: "far fa-fw fa-envelope"
      url: "mailto:glen@glenjohnson.co.uk"
    - label: "+44 (0) 7808 507363"
      icon: "fas fa-fw fa-phone"
      url: "tel:+447808507363"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/Glenjohnsonsax"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/glenjohnsonmusic"

atom_feed:
  hide: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _transcriptions
  - scope:
      path: "_transcriptions"
      type: transcriptions
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  transcriptions:
    output: true
    permalink: /:collection/:path

social:
  type: Person
  name: Glen Johnson
  links: # An array of links to social media profiles
    - "https://www.facebook.com/Glenjohnsonsax"
    - "https://www.instagram.com/glenjohnsonmusic"
